export const ADMIN_ADVERTS_REQUEST = "ADMIN_ADVERTS_REQUEST";
export const ADMIN_ADVERTS_SUCCESS = "ADMIN_ADVERTS_SUCCESS";
export const ADMIN_ADVERTS_FAIL = "ADMIN_ADVERTS_FAIL";

export const ADVERT_DETAILS_REQUEST = "ADVERT_DETAILS_REQUEST";
export const ADVERT_DETAILS_SUCCESS = "ADVERT_DETAILS_SUCCESS";
export const ADVERT_DETAILS_FAIL = "ADVERT_DETAILS_FAIL";

export const CREATE_ADVERT_REQUEST = "CREATE_ADVERT_REQUEST";
export const CREATE_ADVERT_SUCCESS = "CREATE_ADVERT_SUCCESS";
export const CREATE_ADVERT_FAIL = "CREATE_ADVERT_FAIL";
export const CREATE_ADVERT_RESET = "CREATE_ADVERT_RESET";

export const UPDATE_ADVERT_REQUEST = "UPDATE_ADVERT_REQUEST";
export const UPDATE_ADVERT_SUCCESS = "UPDATE_ADVERT_SUCCESS";
export const UPDATE_ADVERT_FAIL = "UPDATE_ADVERT_FAIL";
export const UPDATE_ADVERT_RESET = "UPDATE_ADVERT_RESET";

export const DELETE_ADVERT_REQUEST = "DELETE_ADVERT_REQUEST";
export const DELETE_ADVERT_SUCCESS = "DELETE_ADVERT_SUCCESS";
export const DELETE_ADVERT_FAIL = "DELETE_ADVERT_FAIL";
export const DELETE_ADVERT_RESET = "DELETE_ADVERT_RESET";

export const SELLER_ADVERTS_REQUEST = "SELLER_ADVERTS_REQUEST";
export const SELLER_ADVERTS_SUCCESS = "SELLER_ADVERTS_SUCCESS";
export const SELLER_ADVERTS_FAIL = "SELLER_ADVERTS_FAIL";

export const SELLER_SINGLE_ADVERT_REQUEST = "SELLER_SINGLE_ADVERT_REQUEST";
export const SELLER_SINGLE_ADVERT_SUCCESS = "SELLER_SINGLE_ADVERT_SUCCESS";
export const SELLER_SINGLE_ADVERT_FAIL = "SELLER_SINGLE_ADVERT_FAIL";

export const SELLER_UPDATE_ADVERT_REQUEST = "SELLER_UPDATE_ADVERT_REQUEST";
export const SELLER_UPDATE_ADVERT_SUCCESS = "SELLER_UPDATE_ADVERT_SUCCESS";
export const SELLER_UPDATE_ADVERT_FAIL = "SELLER_UPDATE_ADVERT_FAIL";
export const SELLER_UPDATE_ADVERT_RESET = "SELLER_UPDATE_ADVERT_RESET";

export const SELLER_CREATE_ADVERT_REQUEST = "SELLER_CREATE_ADVERT_REQUEST";
export const SELLER_CREATE_ADVERT_SUCCESS = "SELLER_CREATE_ADVERT_SUCCESS";
export const SELLER_CREATE_ADVERT_FAIL = "SELLER_CREATE_ADVERT_FAIL";
export const SELLER_CREATE_ADVERT_RESET = "SELLER_CREATE_ADVERT_RESET";

export const SELLER_DELETE_ADVERT_REQUEST = "SELLER_DELETE_ADVERT_REQUEST";
export const SELLER_DELETE_ADVERT_SUCCESS = "SELLER_DELETE_ADVERT_SUCCESS";
export const SELLER_DELETE_ADVERT_FAIL = "SELLER_DELETE_ADVERT_FAIL";
export const SELLER_DELETE_ADVERT_RESET = "SELLER_DELETE_ADVERT_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
