export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";

export const REMOVE_TO_CART_SUCCESS = "REMOVE_TO_CART_SUCCESS";
export const REMOVE_TO_CART_FAIL = "REMOVE_TO_CART_FAIL";

export const GET_CART_REQUEST = "REMOVE_TO_CART_REQUEST";
export const GET_CART_SUCCESS = "REMOVE_TO_CART_SUCCESS";
export const GET_CART_FAIL = "REMOVE_TO_CART_FAIL";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";

export const ALL_TEMP_CART = "ALL_TEMP_CART";
export const ID_TEMP_CART = "ID_TEMP_CART";
export const CLEAR_TEMP_CART = "CLEAR_TEMP_CART";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
