export const GET_ALL_FAVOURITE_REQUEST = "GET_ALL_FAVOURITE_REQUEST";
export const GET_ALL_FAVOURITE_SUCCESS = "GET_ALL_FAVOURITE_SUCCESS";
export const GET_ALL_FAVOURITE_FAIL = "GET_ALL_FAVOURITE_FAIL";

export const GET_ALL_VIEW_REQUEST = "GET_ALL_VIEW_REQUEST";
export const GET_ALL_VIEW_SUCCESS = "GET_ALL_VIEW_SUCCESS";
export const GET_ALL_VIEW_FAIL = "GET_ALL_VIEW_FAIL";

export const ADD_FAVOURITE_REQUEST = "ADD_FAVOURITE_REQUEST";
export const ADD_FAVOURITE_SUCCESS = "ADD_FAVOURITE_SUCCESS";
export const ADD_FAVOURITE_FAIL = "ADD_FAVOURITE_FAIL";

export const REMOVE_FAVOURITE_REQUEST = "REMOVE_FAVOURITE_REQUEST";
export const REMOVE_FAVOURITE_SUCCESS = "REMOVE_FAVOURITE_SUCCESS";
export const REMOVE_FAVOURITE_FAIL = "REMOVE_FAVOURITE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
