export const HOME_PRODUCTS_REQUEST = "HOME_PRODUCTS_REQUEST";
export const HOME_PRODUCTS_SUCCESS = "HOME_PRODUCTS_SUCCESS";
export const HOME_PRODUCTS_FAIL = "HOME_PRODUCTS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
