export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAIL = "SEARCH_FAIL";

export const ADMIN_SEARCH_REQUEST = "ADMIN_SEARCH_REQUEST";
export const ADMIN_SEARCH_SUCCESS = "ADMIN_SEARCH_SUCCESS";
export const ADMIN_SEARCH_FAIL = "ADMIN_SEARCH_FAIL";

export const DELETE_SEARCH_REQUEST = "DELETE_SEARCH_REQUEST";
export const DELETE_SEARCH_SUCCESS = "DELETE_SEARCH_SUCCESS";
export const DELETE_SEARCH_FAIL = "DELETE_SEARCH_FAIL";
export const DELETE_SEARCH_RESET = "DELETE_SEARCH_RESET";

export const UPDATE_SEARCH_REQUEST = "UPDATE_SEARCH_REQUEST";
export const UPDATE_SEARCH_SUCCESS = "UPDATE_SEARCH_SUCCESS";
export const UPDATE_SEARCH_FAIL = "UPDATE_SEARCH_FAIL";
export const UPDATE_SEARCH_RESET = "UPDATE_SEARCH_RESET";

export const ADMIN_DELETE_SEARCH_REQUEST = "ADMIN_DELETE_SEARCH_REQUEST";
export const ADMIN_DELETE_SEARCH_SUCCESS = "ADMIN_DELETE_SEARCH_SUCCESS";
export const ADMIN_DELETE_SEARCH_FAIL = "ADMIN_DELETE_SEARCH_FAIL";
export const ADMIN_DELETE_SEARCH_RESET = "ADMIN_DELETE_SEARCH_RESET";

export const ADMIN_CREATE_SEARCH_REQUEST = "ADMIN_CREATE_SEARCH_REQUEST";
export const ADMIN_CREATE_SEARCH_SUCCESS = "ADMIN_CREATE_SEARCH_SUCCESS";
export const ADMIN_CREATE_SEARCH_FAIL = "ADMIN_CREATE_SEARCH_FAIL";
export const ADMIN_CREATE_SEARCH_RESET = "ADMIN_CREATE_SEARCH_RESET";

export const CREATE_SEARCH_REQUEST = "CREATE_SEARCH_REQUEST";
export const CREATE_SEARCH_SUCCESS = "CREATE_SEARCH_SUCCESS";
export const CREATE_SEARCH_FAIL = "CREATE_SEARCH_FAIL";
export const CREATE_SEARCH_RESET = "CREATE_SEARCH_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
