export const SELLER_PRODUCTS_REQUEST = "SELLER_PRODUCTS_REQUEST";
export const SELLER_PRODUCTS_SUCCESS = "SELLER_PRODUCTS_SUCCESS";
export const SELLER_PRODUCTS_FAIL = "SELLER_PRODUCTS_FAIL";

export const SELLER_CREATE_PRODUCT_REQUEST = "SELLER_CREATE_PRODUCT_REQUEST";
export const SELLER_CREATE_PRODUCT_SUCCESS = "SELLER_CREATE_PRODUCT_SUCCESS";
export const SELLER_CREATE_PRODUCT_FAIL = "SELLER_CREATE_PRODUCT_FAIL";
export const SELLER_CREATE_PRODUCT_RESET = "SELLER_CREATE_PRODUCT_RESET";

export const SELLER_UPDATE_PRODUCT_REQUEST = "SELLER_UPDATE_PRODUCT_REQUEST";
export const SELLER_UPDATE_PRODUCT_SUCCESS = "SELLER_UPDATE_PRODUCT_SUCCESS";
export const SELLER_UPDATE_PRODUCT_FAIL = "SELLER_UPDATE_PRODUCT_FAIL";
export const SELLER_UPDATE_PRODUCT_RESET = "SELLER_UPDATE_PRODUCT_RESET";

export const SELLER_DELETE_PRODUCT_REQUEST = "SELLER_DELETE_PRODUCT_REQUEST";
export const SELLER_DELETE_PRODUCT_SUCCESS = "SELLER_DELETE_PRODUCT_SUCCESS";
export const SELLER_DELETE_PRODUCT_FAIL = "SELLER_DELETE_PRODUCT_FAIL";
export const SELLER_DELETE_PRODUCT_RESET = "SELLER_DELETE_PRODUCT_RESET";

export const SELLER_ORDER_REQUEST = "SELLER_ORDER_REQUEST";
export const SELLER_ORDER_SUCCESS = "SELLER_ORDER_SUCCESS";
export const SELLER_ORDER_FAIL = "SELLER_ORDER_FAIL";

export const SELLER_SINGLE_ORDER_REQUEST = "SELLER_SINGLE_ORDER_REQUEST";
export const SELLER_SINGLE_ORDER_SUCCESS = "SELLER_SINGLE_ORDER_SUCCESS";
export const SELLER_SINGLE_ORDER_FAIL = "SELLER_SINGLE_ORDER_FAIL";

export const SELLER_UPDATE_ORDER_REQUEST = "SELLER_UPDATE_ORDER_REQUEST";
export const SELLER_UPDATE_ORDER_SUCCESS = "SELLER_UPDATE_ORDER_SUCCESS";
export const SELLER_UPDATE_ORDER_FAIL = "SELLER_UPDATE_ORDER_FAIL";
export const SELLER_UPDATE_ORDER_RESET = "SELLER_UPDATE_ORDER_RESET";

export const SELLER_DELETE_ORDER_REQUEST = "SELLER_DELETE_ORDER_REQUEST";
export const SELLER_DELETE_ORDER_SUCCESS = "SELLER_DELETE_ORDER_SUCCESS";
export const SELLER_DELETE_ORDER_FAIL = "SELLER_DELETE_ORDER_FAIL";
export const SELLER_DELETE_ORDER_RESET = "SELLER_DELETE_ORDER_RESET";
